config/routes.rb
#  Copyright (c) 2012-2020, Schweizer Blasmusikverband. This file is part of
#  hitobito_sbv and licensed under the Affero General Public License version 3
#  or later. See the COPYING file at the top-level directory or at
#  https://github.com/hitobito/hitobito_sbv.

Rails.application.routes.draw do

  extend LanguageRouteScope

  language_scope do
    # Define wagon routes here

    resources :songs
    resources :groups, only: [] do
      member do
        get :subverein_select
      end

      get 'export_lohnsummen' => 'lohnsummen#show'

      resources :song_counts
      resources :concerts do
        collection do
          post 'submit'
        end
      end

      resources :song_censuses, only: [:new, :create, :index] do
        post 'remind', to: 'song_censuses#remind'
      end
      resource :roles, only: [] do
        post 'create_history_member'
      end
      resources :history_roles, only: [:create, :destroy]
    end
    get '/groups/query' => 'groups/query#index', as: :query_groups

    get 'help' => 'help#index'
  end

end

app/models/person/active_years.rb
# frozen_string_literal: true

#  Copyright (c) 2018-2024, Schweizer Blasmusikverband. This file is part of
#  hitobito_sbv and licensed under the Affero General Public License version 3
#  or later. See the COPYING file at the top-level directory or at
#  https://github.com/hitobito/hitobito_sbv.

module Person::ActiveYears
  extend ActiveSupport::Concern

  included do
    Person::PUBLIC_ATTRS << :active_years
    Person::FILTER_ATTRS << :active_years << [:prognostic_active_years, :integer]
  end

  def prognostic_active_years
    update_active_years if active_years.nil?

    if active_role?
      active_years.succ
    else
      active_years
    end
  end

  def update_active_years
    cache_active_years
    save(validate: false)
  end

  def cache_active_years
    self.active_role = active_member_role?
    self.active_years = calculate_active_years
  end

  private

  def veteran_role_condition
    {
      type: [
        Group::VereinMitglieder::Mitglied,
        Role::MitgliederMitglied
      ].map(&:sti_name)
    }
  end

  def active_member_role?
    roles.where(veteran_role_condition).any?
  end

  def calculate_active_years(end_date = Time.zone.now)
    roles.with_inactive.where(veteran_role_condition).map do |role|
      VeteranYears.new((role.start_on || role.created_at).year, (role.end_on || end_date).year)
    end.sort.sum(VeteranYears::NULL).years.to_i
  end
end

app/models/sbv/person.rb
# frozen_string_literal: true

#  Copyright (c) 2012-2020, Schweizer Blasmusikverband. This file is part of
#  hitobito_sbv and licensed under the Affero General Public License version 3
#  or later. See the COPYING file at the top-level directory or at
#  https://github.com/hitobito/hitobito_sbv.

module Sbv::Person
  extend ActiveSupport::Concern

  included do
    include Person::ActiveYears

    Person::PUBLIC_ATTRS << :personal_data_usage

    validates :first_name, :last_name, presence: true
  end
end

app/controllers/sbv/person/history_controller.rb
# frozen_string_literal: true

#  Copyright (c) 2019, Schweizer Blasmusikverband. This file is part of
#  hitobito_sbv and licensed under the Affero General Public License version 3
#  or later. See the COPYING file at the top-level directory or at
#  https://github.com/hitobito/hitobito_sbv.

module Sbv::Person::HistoryController
  def entry
    super
  rescue ActiveRecord::RecordNotFound => e
    if @group.is_a? Group::Root
      @person = Person.where(primary_group_id: nil).find(params[:id])
    else
      raise e
    end
  end
end

app/views/person/history/_history_columns_sbv.html.haml
- action_col(t) do |role|
  = link_action_destroy(group_history_role_path(@group, role.id)) if can?(:destroy, role)

app/views/person/history/_history_members_form_sbv.html.haml
- #  Copyright (c) 2012-2025, Schweizer Blasmusikverband. This file is part of
- #  hitobito_sbv and licensed under the Affero General Public License version 3
- #  or later. See the COPYING file at the top-level directory or at
- #  https://github.com/hitobito/hitobito_sbv.

- if can?(:create_history_member, @group)
  %br
  .accordion
    %a.btn.btn-sm.btn-outline-primary.accordion-toggle.mb-3.collapsed.header{ href: "#new_role", data: { bs_toggle: :collapse } }
      = t('.new_role')


    .accordion-body.collapse{ id: 'new_role' }
      .accordion-inner
        %fieldset
          %legend
          = standard_form(Role.new, url: group_history_roles_path(@group)) do |f|
            .col-6
              = f.hidden_field(:person_id, value: @person.id)

              = swappable_group_add_fieldset(:create_deleted_verein, :select_existing_verein) do
                = f.labeled(:verein, t('.verein')) do
                  = f.group_field :group, search_params: { historic: true }
                = f.labeled_input_field(:label,
                                        data: { provide: :typeahead, source: Role.available_labels })

              = swappable_group_add_fieldset(:select_existing_verein, :create_deleted_verein) do
                = f.fields_for(:group, Group.new) do |fields|
                  = fields.labeled_input_fields :name

              = field_set_tag  do
                = f.labeled(:start_date, t('.start_date')) do
                  = f.date_field(:start_on, name: 'role[start_on]', autocomplete: 'off')

                = f.labeled(:end_date, t('.end_date')) do
                  = f.date_field(:end_on, name: 'role[end_on]', autocomplete: 'off')

              = f.indented do
                = submit_button(f, t('.save'))