config/routes.rb
#  Copyright (c) 2012-2020, Schweizer Blasmusikverband. This file is part of
#  hitobito_sbv and licensed under the Affero General Public License version 3
#  or later. See the COPYING file at the top-level directory or at
#  https://github.com/hitobito/hitobito_sbv.

Rails.application.routes.draw do

  extend LanguageRouteScope

  language_scope do
    # Define wagon routes here

    resources :songs
    resources :groups, only: [] do
      member do
        get :subverein_select
      end

      get 'export_lohnsummen' => 'lohnsummen#show'

      resources :song_counts
      resources :concerts do
        collection do
          post 'submit'
        end
      end

      resources :song_censuses, only: [:new, :create, :index] do
        post 'remind', to: 'song_censuses#remind'
      end
      resource :roles, only: [] do
        post 'create_history_member'
      end
      resources :history_roles, only: [:create, :destroy]
    end
    get '/groups/query' => 'groups/query#index', as: :query_groups

    get 'help' => 'help#index'
  end

end

app/models/group/generalverband.rb
# frozen_string_literal: true

#  Copyright (c) 2019-2020, Schweizer Blasmusikverband. This file is part of
#  hitobito_sbv and licensed under the Affero General Public License version 3
#  or later. See the COPYING file at the top-level directory or at
#  https://github.com/hitobito/hitobito_sbv.

# == Schema Information
#
# Table name: groups
#
#  id                          :integer          not null, primary key
#  parent_id                   :integer
#  lft                         :integer
#  rgt                         :integer
#  name                        :string(255)      not null
#  short_name                  :string(31)
#  type                        :string(255)      not null
#  email                       :string(255)
#  address                     :string(1024)
#  zip_code                    :integer
#  town                        :string(255)
#  country                     :string(255)
#  contact_id                  :integer
#  created_at                  :datetime
#  updated_at                  :datetime
#  deleted_at                  :datetime
#  layer_group_id              :integer
#  creator_id                  :integer
#  updater_id                  :integer
#  deleter_id                  :integer
#  require_person_add_requests :boolean          default(FALSE), not null
#  vereinssitz                 :string(255)
#  founding_year               :integer
#  correspondence_language     :string(5)
#  besetzung                   :string(255)
#  klasse                      :string(255)
#  unterhaltungsmusik          :string(255)
#  subventionen                :string(255)
#  swoffice_id                 :integer
#  secondary_parent_id         :integer
#  tertiary_parent_id          :integer
#  description                 :text(65535)
#  logo                        :string(255)
#  hostname                    :string(255)
#

class Group::Generalverband < ::Group
  self.layer = true
  self.event_types = [] # only managing structure, does not have events (as of 2019-06-17)

  children Group::Root

  class Admin < Role::Admin
    self.permissions = [:layer_and_below_full, :admin, :impersonation, :finance, :uv_lohnsumme]
  end

  roles Admin
end

app/models/group/kreis.rb
# frozen_string_literal: true

#  Copyright (c) 2022, Schweizer Blasmusikverband. This file is part of
#  hitobito_sbv and licensed under the Affero General Public License version 3
#  or later. See the COPYING file at the top-level directory or at
#  https://github.com/hitobito/hitobito_sbv.
# == Schema Information
#
# Table name: groups
#
#  id                          :integer          not null, primary key
#  parent_id                   :integer
#  lft                         :integer
#  rgt                         :integer
#  name                        :string(255)      not null
#  short_name                  :string(31)
#  type                        :string(255)      not null
#  email                       :string(255)
#  address                     :string(1024)
#  zip_code                    :integer
#  town                        :string(255)
#  country                     :string(255)
#  contact_id                  :integer
#  created_at                  :datetime
#  updated_at                  :datetime
#  deleted_at                  :datetime
#  layer_group_id              :integer
#  creator_id                  :integer
#  updater_id                  :integer
#  deleter_id                  :integer
#  require_person_add_requests :boolean          default(FALSE), not null
#  vereinssitz                 :string(255)
#  founding_year               :integer
#  correspondence_language     :string(5)
#  besetzung                   :string(255)
#  klasse                      :string(255)
#  unterhaltungsmusik          :string(255)
#  subventionen                :string(255)
#  swoffice_id                 :integer
#  secondary_parent_id         :integer
#  tertiary_parent_id          :integer
#  description                 :text(65535)
#  logo                        :string(255)
#  hostname                    :string(255)
#

class Group::Kreis < ::Group
  self.layer = true
  self.default_children = [Group::KreisGeschaeftsstelle,
    Group::KreisVorstand,
    Group::KreisKontakte,
    Group::KreisMusikkommission]

  children Group::KreisGeschaeftsstelle,
    Group::KreisVorstand,
    Group::KreisMusikkommission,
    Group::KreisKontakte,
    Group::Verein

  ### ROLES

  class Admin < Role::Admin
    self.permissions = [:layer_and_below_full]
  end

  class SuisaAdmin < Role::SuisaAdmin
  end

  roles Admin, SuisaAdmin
end

app/models/group/kreis_geschaeftsstelle.rb
# frozen_string_literal: true

#  Copyright (c) 2022, Schweizer Blasmusikverband. This file is part of
#  hitobito_sbv and licensed under the Affero General Public License version 3
#  or later. See the COPYING file at the top-level directory or at
#  https://github.com/hitobito/hitobito_sbv.
# == Schema Information
#
# Table name: groups
#
#  id                          :integer          not null, primary key
#  parent_id                   :integer
#  lft                         :integer
#  rgt                         :integer
#  name                        :string(255)      not null
#  short_name                  :string(31)
#  type                        :string(255)      not null
#  email                       :string(255)
#  address                     :string(1024)
#  zip_code                    :integer
#  town                        :string(255)
#  country                     :string(255)
#  contact_id                  :integer
#  created_at                  :datetime
#  updated_at                  :datetime
#  deleted_at                  :datetime
#  layer_group_id              :integer
#  creator_id                  :integer
#  updater_id                  :integer
#  deleter_id                  :integer
#  require_person_add_requests :boolean          default(FALSE), not null
#  vereinssitz                 :string(255)
#  founding_year               :integer
#  correspondence_language     :string(5)
#  besetzung                   :string(255)
#  klasse                      :string(255)
#  unterhaltungsmusik          :string(255)
#  subventionen                :string(255)
#  swoffice_id                 :integer
#  secondary_parent_id         :integer
#  tertiary_parent_id          :integer
#  description                 :text(65535)
#  logo                        :string(255)
#  hostname                    :string(255)
#

class Group::KreisGeschaeftsstelle < Group
  class Manager < Role::GeschaeftsstelleManager
  end

  class Staff < Role::GeschaeftsstelleStaff
  end

  class Help < Role::GeschaeftsstelleHelp
  end

  self.standard_role = Staff
  roles Manager, Staff, Help
end

app/models/group/kreis_kontakte.rb
# frozen_string_literal: true

#  Copyright (c) 2022, Schweizer Blasmusikverband. This file is part of
#  hitobito_sbv and licensed under the Affero General Public License version 3
#  or later. See the COPYING file at the top-level directory or at
#  https://github.com/hitobito/hitobito_sbv.
# == Schema Information
#
# Table name: groups
#
#  id                          :integer          not null, primary key
#  parent_id                   :integer
#  lft                         :integer
#  rgt                         :integer
#  name                        :string(255)      not null
#  short_name                  :string(31)
#  type                        :string(255)      not null
#  email                       :string(255)
#  address                     :string(1024)
#  zip_code                    :integer
#  town                        :string(255)
#  country                     :string(255)
#  contact_id                  :integer
#  created_at                  :datetime
#  updated_at                  :datetime
#  deleted_at                  :datetime
#  layer_group_id              :integer
#  creator_id                  :integer
#  updater_id                  :integer
#  deleter_id                  :integer
#  require_person_add_requests :boolean          default(FALSE), not null
#  vereinssitz                 :string(255)
#  founding_year               :integer
#  correspondence_language     :string(5)
#  besetzung                   :string(255)
#  klasse                      :string(255)
#  unterhaltungsmusik          :string(255)
#  subventionen                :string(255)
#  swoffice_id                 :integer
#  secondary_parent_id         :integer
#  tertiary_parent_id          :integer
#  description                 :text(65535)
#  logo                        :string(255)
#  hostname                    :string(255)
#

class Group::KreisKontakte < Group
  children Group::RegionalverbandKontakte

  class Adressverwaltung < Role::Adressverwaltung
  end

  class Kontakt < Role::Kontakt
  end

  self.standard_role = Kontakt
  roles Adressverwaltung, Kontakt
end

app/models/group/kreis_musikkommission.rb
# frozen_string_literal: true

#  Copyright (c) 2022, Schweizer Blasmusikverband. This file is part of
#  hitobito_sbv and licensed under the Affero General Public License version 3
#  or later. See the COPYING file at the top-level directory or at
#  https://github.com/hitobito/hitobito_sbv.
# == Schema Information
#
# Table name: groups
#
#  id                          :integer          not null, primary key
#  parent_id                   :integer
#  lft                         :integer
#  rgt                         :integer
#  name                        :string(255)      not null
#  short_name                  :string(31)
#  type                        :string(255)      not null
#  email                       :string(255)
#  address                     :string(1024)
#  zip_code                    :integer
#  town                        :string(255)
#  country                     :string(255)
#  contact_id                  :integer
#  created_at                  :datetime
#  updated_at                  :datetime
#  deleted_at                  :datetime
#  layer_group_id              :integer
#  creator_id                  :integer
#  updater_id                  :integer
#  deleter_id                  :integer
#  require_person_add_requests :boolean          default(FALSE), not null
#  vereinssitz                 :string(255)
#  founding_year               :integer
#  correspondence_language     :string(5)
#  besetzung                   :string(255)
#  klasse                      :string(255)
#  unterhaltungsmusik          :string(255)
#  subventionen                :string(255)
#  swoffice_id                 :integer
#  secondary_parent_id         :integer
#  tertiary_parent_id          :integer
#  description                 :text(65535)
#  logo                        :string(255)
#  hostname                    :string(255)
#

class Group::KreisMusikkommission < Group
  class Praesident < Role::MusikkommissionPraesident
  end

  class Mitglied < Role::MusikkommissionMitglied
  end

  self.standard_role = Mitglied
  roles Praesident, Mitglied
end

app/models/group/kreis_vorstand.rb
# frozen_string_literal: true

#  Copyright (c) 2022, Schweizer Blasmusikverband. This file is part of
#  hitobito_sbv and licensed under the Affero General Public License version 3
#  or later. See the COPYING file at the top-level directory or at
#  https://github.com/hitobito/hitobito_sbv.
# == Schema Information
#
# Table name: groups
#
#  id                          :integer          not null, primary key
#  parent_id                   :integer
#  lft                         :integer
#  rgt                         :integer
#  name                        :string(255)      not null
#  short_name                  :string(31)
#  type                        :string(255)      not null
#  email                       :string(255)
#  address                     :string(1024)
#  zip_code                    :integer
#  town                        :string(255)
#  country                     :string(255)
#  contact_id                  :integer
#  created_at                  :datetime
#  updated_at                  :datetime
#  deleted_at                  :datetime
#  layer_group_id              :integer
#  creator_id                  :integer
#  updater_id                  :integer
#  deleter_id                  :integer
#  require_person_add_requests :boolean          default(FALSE), not null
#  vereinssitz                 :string(255)
#  founding_year               :integer
#  correspondence_language     :string(5)
#  besetzung                   :string(255)
#  klasse                      :string(255)
#  unterhaltungsmusik          :string(255)
#  subventionen                :string(255)
#  swoffice_id                 :integer
#  secondary_parent_id         :integer
#  tertiary_parent_id          :integer
#  description                 :text(65535)
#  logo                        :string(255)
#  hostname                    :string(255)
#

class Group::KreisVorstand < Group
  class Praesident < Role::VorstandPraesident
  end

  class VizePraesident < Role::VorstandVizePraesident
  end

  class Kassier < Role::VorstandKassier
  end

  class Veteranenchef < Role::VorstandVeteranenchef
  end

  class Mitglied < Role::VorstandMitglied
  end

  self.standard_role = Mitglied
  roles Praesident, VizePraesident, Kassier, Veteranenchef, Mitglied
end

app/models/group/mitgliederverband.rb
# frozen_string_literal: true

#  Copyright (c) 2012-2020, Schweizer Blasmusikverband. This file is part of
#  hitobito_sbv and licensed under the Affero General Public License version 3
#  or later. See the COPYING file at the top-level directory or at
#  https://github.com/hitobito/hitobito_sbv.

# == Schema Information
#
# Table name: groups
#
#  id                          :integer          not null, primary key
#  parent_id                   :integer
#  lft                         :integer
#  rgt                         :integer
#  name                        :string(255)      not null
#  short_name                  :string(31)
#  type                        :string(255)      not null
#  email                       :string(255)
#  address                     :string(1024)
#  zip_code                    :integer
#  town                        :string(255)
#  country                     :string(255)
#  contact_id                  :integer
#  created_at                  :datetime
#  updated_at                  :datetime
#  deleted_at                  :datetime
#  layer_group_id              :integer
#  creator_id                  :integer
#  updater_id                  :integer
#  deleter_id                  :integer
#  require_person_add_requests :boolean          default(FALSE), not null
#  vereinssitz                 :string(255)
#  founding_year               :integer
#  correspondence_language     :string(5)
#  besetzung                   :string(255)
#  klasse                      :string(255)
#  unterhaltungsmusik          :string(255)
#  subventionen                :string(255)
#  swoffice_id                 :integer
#  secondary_parent_id         :integer
#  tertiary_parent_id          :integer
#  description                 :text(65535)
#  logo                        :string(255)
#  hostname                    :string(255)
#

class Group::Mitgliederverband < ::Group
  self.layer = true
  self.default_children = [Group::MitgliederverbandGeschaeftsstelle,
    Group::MitgliederverbandVorstand,
    Group::MitgliederverbandKontakte,
    Group::MitgliederverbandMusikkommission,
    Group::MitgliederverbandVeteranen]

  self.event_types += [Event::Course]

  children Group::MitgliederverbandGeschaeftsstelle,
    Group::MitgliederverbandVorstand,
    Group::MitgliederverbandMusikkommission,
    Group::MitgliederverbandArbeitsgruppe,
    Group::MitgliederverbandKontakte,
    Group::MitgliederverbandVeteranen,
    Group::Regionalverband,
    Group::Verein

  include SecondaryChildren

  ### ROLES

  class Admin < Role::Admin
    self.permissions = [:layer_and_below_full, :uv_lohnsumme]
  end

  class SuisaAdmin < Role::SuisaAdmin
  end

  roles Admin, SuisaAdmin
end

app/views/groups/_actions_show_sbv.html.haml
-#  Copyright (c) 2020, Schweizer Blasmusikverband. This file is part of
-#  hitobito_sbv and licensed under the Affero General Public License version 3
-#  or later. See the COPYING file at the top-level directory or at
-#  https://github.com/hitobito/hitobito_sbv.

- if can?(:show_uv_lohnsummen, entry)
  = action_button(t('.export_lohnsummen'), group_export_lohnsummen_path(group_id: entry.id, format: :csv), :download)
- if entry.layer? && can?(:subverein_select, entry)
  = action_button(translate('.create_verein_invoice_run'),
    subverein_select_group_path(entry),
    :plus,
    data: { checkable: true, method: :get },
    remote: true)

app/views/groups/_aside_sbv.html.haml
-#  Copyright (c) 2019, Schweizer Blasmusikverband. This file is part of
-#  hitobito_sbv and licensed under the Affero General Public License version 3
-#  or later. See the COPYING file at the top-level directory or at
-#  https://github.com/hitobito/hitobito_sbv.

= section_table(Group.human_attribute_name(:secondary_parent_groups), entry.secondary_parents) do |item|
  %td
    = link_to(item.to_s, group_path(item.id))

app/views/groups/_attrs_sbv.html.haml
-#  Copyright (c) 2012-2018, Schweizer Blasmusikverband. This file is part of
-#  hitobito_sbv and licensed under the Affero General Public License version 3
-#  or later. See the COPYING file at the top-level directory or at
-#  https://github.com/hitobito/hitobito_sbv.

= render_attrs(entry, *entry.used_attributes(:correspondence_language, :vereinssitz, :founding_year, :besetzung, :klasse, :unterhaltungsmusik))
= render_attrs(entry, *entry.used_attributes(:subventionen)) if can?(:show_details, @group)
= render_attrs(entry, *entry.used_attributes(:buv_lohnsumme, :nbuv_lohnsumme)) if can?(:show_uv_lohnsummen, @group)
- if entry.uses_manually_counted_members?
  = render_attrs(entry, *entry.used_attributes(:manual_member_count))
- else
  = render_attrs(entry, *entry.used_attributes(:recognized_members))

- if entry.is_a?(Group::Root)
  = render_attrs(entry, :hostname)

app/views/groups/_fields_sbv.html.haml
-#  Copyright (c) 2012-2019, Schweizer Blasmusikverband. This file is part of
-#  hitobito_sbv and licensed under the Affero General Public License version 3
-#  or later. See the COPYING file at the top-level directory or at
-#  https://github.com/hitobito/hitobito_sbv.


- if entry.is_a?(Group::Verein)
  = field_set_tag do
    = f.labeled_input_fields :manual_member_count if entry.manually_counted_members?
    = f.labeled_input_fields :vereinssitz, :founding_year
    = f.labeled_collection_select(:correspondence_language, Settings.application.languages.to_hash.merge(Settings.application.additional_languages&.to_hash || {}), :first, :last, {}, class: 'form-select form-select-sm')
    = f.labeled_collection_select(:besetzung, Group.besetzung_labels.to_a, :first, :last, { include_blank: "" }, class:'form-select form-select-sm')
    = f.labeled_collection_select(:klasse, Group.klasse_labels.to_a, :first, :last, { include_blank: "" }, class:'form-select form-select-sm')
    = f.labeled_collection_select(:unterhaltungsmusik, Group.unterhaltungsmusik_labels.to_a, :first, :last, { include_blank: "" }, class:'form-select form-select-sm')

  = field_set_tag do
    = f.labeled_input_fields :subventionen

  - if can?(:edit_uv_lohnsummen, entry)
    = field_set_tag do
      = f.labeled_input_fields :buv_lohnsumme, :nbuv_lohnsumme

  = field_set_tag Group.human_attribute_name(:secondary_parent_groups) do
    = f.labeled_collection_select :secondary_parent_id, Group.secondary_parents, :id, :name, { include_blank: "" }, class:'form-select form-select-sm'
    = f.labeled_collection_select :tertiary_parent_id, Group.secondary_parents, :id, :name, { include_blank: "" }, class:'form-select form-select-sm'

- if entry.is_a?(Group::Root)
  = field_set_tag do
    = f.labeled_input_fields :hostname

app/views/groups/_subgroup_select_modal.html.haml
- #  Copyright (c) 2023, Schweizer Blasmusikverband. This file is part of
- #  hitobito_sbv and licensed under the Affero General Public License version 3
- #  or later. See the COPYING file at the top-level directory or at
- #  https://github.com/hitobito/hitobito_sbv.

#subgroup-select.modal.fade
  .modal-dialog
    .modal-content
      .modal-header
        %h5.bold.modal-title
          %b= t('groups.actions_show_sbv.create_verein_invoice_list')

      = standard_form(entry,
        url: new_group_invoice_list_path(group_id: entry) , method: :get) do |f|
        .modal-body
          .row-fluid
            = hidden_field_tag('invoice_items[]', [:membership_fee])
            .checkboxes
              - groups = Group::Verein.where(id: entry.descendants.pluck(:id))
              - if groups.present?
                = label_tag(nil, class: 'checkbox') do
                  = check_box_tag(:all, 0, true, data: :multiselect)
                  = t('.select_all')

                = subgroups_checkboxes(groups, entry)
              - else
                = t('.no_entries')
        .modal-footer
          = submit_button(f, t('.submit'), data: { checkable: true })
          = link_to(ti('button.cancel'), nil,
            class: 'link cancel',
            onclick: "event.preventDefault(); $('#subgroup-select').modal('hide')")

app/views/groups/_subverein_select_modal.html.haml
- #  Copyright (c) 2023, Schweizer Blasmusikverband. This file is part of
- #  hitobito_sbv and licensed under the Affero General Public License version 3
- #  or later. See the COPYING file at the top-level directory or at
- #  https://github.com/hitobito/hitobito_sbv.

#subgroup-select.modal.fade
  .modal-dialog
    .modal-content
      .modal-header
        %h5.bold.modal-title
          %b= t('groups.actions_show_sbv.create_verein_invoice_run')

      = standard_form(entry,
        url: new_group_invoice_run_path(group_id: entry) , method: :get) do |f|
        .modal-body
          .row-fluid
            = hidden_field_tag('invoice_items[]', [:membership_fee])
            .checkboxes
              = subverein_checkboxes(entry)
        .modal-footer
          - groups = Group::Verein.where(id: entry.descendants.pluck(:id))
          - if groups.present?
            - disabled_text = entry.invoice_config.invalid? ? t('.invoice_config_invalid') : nil
            = submit_button(f, t('.submit'), data: { checkable: true }, disabled: disabled_text.present?, title: disabled_text)
          = link_to(ti('button.cancel'), nil,
            class: 'link cancel',
            onclick: "event.preventDefault(); $('#subgroup-select').modal('hide')")

app/views/groups/subgroup_select.js.haml
- #  Copyright (c) 2023, Schweizer Blasmusikverband. This file is part of
- #  hitobito_sbv and licensed under the Affero General Public License version 3
- #  or later. See the COPYING file at the top-level directory or at
- #  https://github.com/hitobito/hitobito_sbv.

$('#modal-placeholder').html("#{escape_javascript(render('subgroup_select_modal'))}")
$('#subgroup-select').modal('show')

app/views/groups/subverein_select.js.haml
- #  Copyright (c) 2023, Schweizer Blasmusikverband. This file is part of
- #  hitobito_sbv and licensed under the Affero General Public License version 3
- #  or later. See the COPYING file at the top-level directory or at
- #  https://github.com/hitobito/hitobito_sbv.

$('#modal-placeholder').html("#{escape_javascript(render('subverein_select_modal'))}")
$('#subgroup-select').modal('show')