config/routes.rb
#  Copyright (c) 2012-2020, Schweizer Blasmusikverband. This file is part of
#  hitobito_sbv and licensed under the Affero General Public License version 3
#  or later. See the COPYING file at the top-level directory or at
#  https://github.com/hitobito/hitobito_sbv.

Rails.application.routes.draw do

  extend LanguageRouteScope

  language_scope do
    # Define wagon routes here

    resources :songs
    resources :groups, only: [] do
      member do
        get :subverein_select
      end

      get 'export_lohnsummen' => 'lohnsummen#show'

      resources :song_counts
      resources :concerts do
        collection do
          post 'submit'
        end
      end

      resources :song_censuses, only: [:new, :create, :index] do
        post 'remind', to: 'song_censuses#remind'
      end
      resource :roles, only: [] do
        post 'create_history_member'
      end
      resources :history_roles, only: [:create, :destroy]
    end
    get '/groups/query' => 'groups/query#index', as: :query_groups

    get 'help' => 'help#index'
  end

end

app/controllers/song_censuses_controller.rb
# frozen_string_literal: true

#  Copyright (c) 2012-2018, Schweizer Blasmusikverband. This file is part of
#  hitobito_sbv and licensed under the Affero General Public License version 3
#  or later. See the COPYING file at the top-level directory or at
#  https://github.com/hitobito/hitobito_sbv.

class SongCensusesController < CrudController
  include YearBasedPaging

  self.permitted_attrs = [:year, :start_at, :finish_at]

  helper_method :group

  skip_authorize_resource
  before_action :authorize_class
  around_create :switch_census_period

  def index
    @census = SongCensus.where(year: year).last
    @total = CensusCalculator.new(@census, group).total
  end

  def create
    super(location: group_song_censuses_path(group))
  end

  def remind
    census = SongCensus.find(params[:song_census_id])
    vereins_total = CensusCalculator.new(census, group).vereins_total
    count = deliver_reminders(vereins_total)

    redirect_back(
      fallback_location: group_song_censuses_path(group, census),
      notice: t(".success", verein_count: count)
    )
  end

  private

  def authorize_class
    authorize!(:manage_song_census, group)
  end

  def group
    @group ||= Group.find(params[:group_id])
  end

  def default_year
    @default_year ||= SongCensus.current.try(:year) || current_year
  end

  def current_year
    @current_year ||= Time.zone.today.year
  end

  def year_range
    @year_range ||= (year - 3)..(year + 1)
  end

  def switch_census_period
    old = SongCensus.current
    return false unless yield

    new = SongCensus.current

    CensusPeriodSwitch.new(old, new).perform
  end

  # extracted methods

  def deliver_reminders(vereins_total)
    group.descendants.where(type: Group::Verein.sti_name).collect do |verein|
      next if vereins_total[verein.id]

      verein.suisa_admins.each do |suisa_admin|
        next if Person.mailing_emails_for(suisa_admin).blank?

        SongCensusMailer.reminder(suisa_admin, verein).deliver_now
      end
    end.compact.count
  end
end

app/helpers/song_censuses_helper.rb
# frozen_string_literal: true

#  Copyright (c) 2020-2022, Schweizer Blasmusikverband. This file is part of
#  hitobito_sbv and licensed under the Affero General Public License version 3
#  or later. See the COPYING file at the top-level directory or at
#  https://github.com/hitobito/hitobito_sbv.

module SongCensusesHelper
  def census_submitted_ratio(verband, total)
    census_submitted = total[verband.id].to_a.size
    census_total = verband.descendants.without_deleted.where(type: Group::Verein.sti_name).size

    # return t('.census_complete') if census_submitted == census_total
    t(".censuses_submitted", submitted: census_submitted, total: census_total)
  end

  def census_finish_button(census, group_id)
    if census.try(:current?) && census.finished?
      action_button(
        t("song_censuses.finish.submit"),
        new_group_song_census_path(group_id),
        :ok,
        data: {confirm: t("song_censuses.finish.start_new_census")}
      )
    end
  end

  def census_submit_button(concerts, group)
    if concerts.none?
      inactive_census_submit("none")
    elsif concerts.all?(&:song_census)
      inactive_census_submit("submitted")
    else
      active_census_submit("submit", submit_group_concerts_path(group))
    end
  end

  private

  def census_submit_label(key)
    t("song_censuses.submit_button.label.#{key}")
  end

  def census_submit_tooltip(key)
    t("song_censuses.submit_button.tooltip.#{key}")
  end

  def active_census_submit(key, url)
    action_button(
      census_submit_label(key), url, nil,
      method: :post, title: census_submit_tooltip(key)
    )
  end

  def inactive_census_submit(key)
    content_tag(:div, class: "tooltip-wrapper", title: census_submit_tooltip(key)) do
      action_button(census_submit_label(key), "#", nil, class: "disabled")
    end
  end
end

app/views/song_censuses/_actions_index.html.haml
= render 'remind'
= render 'finish'

- if can?(:manage_song_census, group)
  = song_counts_export_dropdown

app/views/song_censuses/_finish.html.haml
- if can?(:manage_song_census, @group)
  = census_finish_button(@census, @group.id)

app/views/song_censuses/_form.html.haml
-#
  Copyright (c) 2018, Schweizer Blasmusikverband. This file is part of
  hitobito_sbv and licensed under the Affero General Public License version 3
  or later. See the COPYING file at the top-level directory or at
  https://github.com/hitobito/hitobito_sbv.

= crud_form [group, entry],
  :year, :start_at, :finish_at,
  cancel_url: group_song_censuses_path(group)

app/views/song_censuses/_remind.html.haml
- if can?(:manage_song_census, @group) && @census.try(:reminder_period?)
  = action_button(t('.send'), group_song_census_remind_path(@group.id, @census), :envelope,
    { data: { confirm: "#{t('.send_confirm')}" }, method: 'post' })

app/views/song_censuses/_totals.html.haml
- mitgliederverbaende = @group.descendants.without_deleted.where(type: Group::Mitgliederverband.sti_name).order(:name)
- regionalverbaende   = @group.descendants.without_deleted.where(type: Group::Regionalverband.sti_name).order(:name)
- vereine             = @group.children.without_deleted.where(type: Group::Verein.sti_name).order(:name)

- if mitgliederverbaende.any?
  %h2
    =t('activerecord.models.group/mitgliederverband.other')

  = table(mitgliederverbaende, class: 'table table-striped table-hover') do |t|
    - t.col do |verband|
      = link_to(verband.name, group_song_censuses_path(verband, year: year))

    - t.col do |verband|
      = census_submitted_ratio(verband, @total[:mitgliederverband])

- if regionalverbaende.any?
  %h2
    =t('activerecord.models.group/regionalverband.other')

  = table(regionalverbaende, class: 'table table-striped table-hover') do |t|
    - t.col do |verband|
      = link_to(verband.name, group_song_censuses_path(verband, year: year))
    - t.col do |verband|
      = census_submitted_ratio(verband, @total[:regionalverband])

- if vereine.any?
  %h2
    =t('activerecord.models.group/verein.other')

  = table(vereine, class: 'table table-striped table-hover') do |t|
    - t.col do |verein|
      = link_to(verein.name, group_song_censuses_path(verein, year: year))
    - t.col do |verein|
      = t(".#{@total[:verein][verein.id].presence || 'not_submitted'}")

app/views/song_censuses/index.html.haml
= content_for(:toolbar, render('actions_index'))
= render 'shared/page_per_year'

#main.row
  - if @total
    %article.col-8
      = render 'totals'

  - else
    %p= t('.no_data_for_this_year')